# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'DemoSYTools' do
  use_frameworks!

  pod 'FMDB'
  pod 'LKDBHelper'
  pod 'IQKeyboardManager', '~> 4.0.0'
  pod 'SAMKeychain'
  pod 'SDWebImage'
  pod 'MBProgressHUD'
  pod 'RegexKitLite'
  pod 'Masonry'
  pod 'ReactiveCocoa'
  pod 'MJRefresh'
  pod 'YYModel'
  pod 'AFNetworking'
  pod 'YYKit'

end
